### ISSUE TITLE
Integrity constraint violation

### ISSUE THREAD

**Issue by niners52** [galacticlabs/customer-group-payment-filters#1]
I am on Magento 2.2.6. I installed using composer. I want to restrict the Net30 payment to only on the Net30 customer group. When I save customer group I get this error-

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '7912-0-1' for key 'PRIMARY', query was: INSERT INTO `catalog_product_index_price` SELECT `index`.`entity_id`, 0 AS customer_group_id, `index`.`website_id`, `index`.`tax_class_id`, `index`.`price`, `index`.`final_price`, `index`.`min_price`, `index`.`max_price`, `index`.`tier_price` FROM `catalog_product_index_price` AS `index` WHERE (customer_group_id = '4') ORDER BY `index`.`entity_id` ASC, `index`.`customer_group_id` ASC, `index`.`website_id` ASC LIMIT 50000

Any Ideas?

**Comment by alanablett** [comment]
Hi @niners52 

Sorry but this error sounds like it may be coming from another module or somewhere else?! There would be no reason for the table `catalog_product_index_price` to be affected by this module. The module has been installed and tested on a fresh version of 2.2.6. I'd suggest maybe looking through the stack trace to see where this error is occurring.

You could also try disabling this module, flushing all the usual caches etc... and saving the Customer Group to make sure this issue only occurs when the module is enabled.

Let me know if the issue persists and we'll try to resolve 🙂

**Comment by niners52** [comment]
I started troubleshooting and walked through everything one more time and it worked. Not sure what I screwed up the first time around but it is working now. Thank you for the response and the extension!
